<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SafeguardSystem.Common\SafeguardSystem.Common.csproj"/>
        <ProjectReference Include="..\SafeguardSystem.DAL\SafeguardSystem.DAL.csproj"/>
    </ItemGroup>

</Project>
