// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeguardSystem.DAL;

#nullable disable

namespace SafeguardSystem.DAL.Migrations
{
    [DbContext(typeof(SafeguardDbContext))]
    [Migration("20250228192803_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Business", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ContractExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("BusinessId");

                    b.HasIndex("UserId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Checkpoint", b =>
                {
                    b.Property<Guid>("CheckpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CheckpointId");

                    b.HasIndex("LocationId");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Contract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.HasKey("ContractId");

                    b.HasIndex("TeamId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("LocationId");

                    b.HasIndex("BusinessId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshTokenKey")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Refreshtokens");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("d1616b66-90cc-479f-b45e-1e86378937f7"),
                            RoleName = "Security Guard"
                        },
                        new
                        {
                            RoleId = new Guid("7a04e1d4-c176-467d-ac7d-6e1433ce6f3e"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("6be95231-36aa-4a26-8c61-b65e040ec32a"),
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = new Guid("be19e4b3-6664-4afd-9ebb-98e0a073edc9"),
                            RoleName = "Business Partner"
                        });
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityGuard", b =>
                {
                    b.Property<Guid>("GuardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("GuardId");

                    b.HasIndex("UserId");

                    b.ToTable("SecurityGuards");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityShift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("ShiftId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TypeId");

                    b.ToTable("SecurityShifts");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GuardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("char(36)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("GuardId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftIncident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Envidence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("IncidentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IncidentId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("ShiftIncidents");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftType", b =>
                {
                    b.Property<Guid>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TIME(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TIME(6)");

                    b.HasKey("TypeId");

                    b.ToTable("ShiftTypes");

                    b.HasData(
                        new
                        {
                            TypeId = new Guid("4112683c-a85f-4429-b6ac-292ca9364155"),
                            Description = "Morning shift",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsDeleted = false,
                            Name = "Morning",
                            StartTime = new TimeSpan(0, 5, 0, 0, 0)
                        },
                        new
                        {
                            TypeId = new Guid("c333cd26-e186-445b-969f-e2fc983b18b8"),
                            Description = "Afternoon shift",
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            IsDeleted = false,
                            Name = "Afternoon",
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TypeId = new Guid("cdbb6b9e-c537-4659-b909-60712082038d"),
                            Description = "Night shift",
                            EndTime = new TimeSpan(0, 2, 0, 0, 0),
                            IsDeleted = false,
                            Name = "Night",
                            StartTime = new TimeSpan(0, 19, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GuardId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TeamId");

                    b.HasIndex("GuardId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ActivationTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "58sErANL7bbv096ghTnNN3qIiqX2",
                            Avatar = "https://www.freepik.com/free-vector/simple-vibing-cat-square-meme_58459053.htm#fromView=keyword&page=1&position=0&uuid=f4bd18ef-8de6-4b6e-8e68-06073abf526b&query=Animal+Memes",
                            BirthDay = new DateTime(2004, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@test.com",
                            FullName = "Viet Anh",
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            Phone = "0123456789",
                            RoleID = new Guid("7a04e1d4-c176-467d-ac7d-6e1433ce6f3e"),
                            UserName = "Admin"
                        },
                        new
                        {
                            UserId = "UCdsPNEZpKeUlbPE8q478r60f5o1",
                            Avatar = "https://www.freepik.com/free-vector/simple-vibing-cat-square-meme_58459053.htm#fromView=keyword&page=1&position=0&uuid=f4bd18ef-8de6-4b6e-8e68-06073abf526b&query=Animal+Memes",
                            BirthDay = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager@test.com",
                            FullName = "Nhat Nam",
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            Phone = "0123456789",
                            RoleID = new Guid("6be95231-36aa-4a26-8c61-b65e040ec32a"),
                            UserName = "Manager"
                        });
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Business", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.User", "User")
                        .WithMany("Businesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Checkpoint", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Location", "Location")
                        .WithMany("Checkpoints")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Contract", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Team", "Team")
                        .WithMany("Contracts")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Location", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Business", "Business")
                        .WithMany("Locations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityGuard", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.User", "User")
                        .WithMany("SecurityGuards")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityShift", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Location", "Location")
                        .WithMany("SecurityShifts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeguardSystem.DAL.Entities.Team", "Team")
                        .WithMany("SecurityShifts")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeguardSystem.DAL.Entities.ShiftType", "Type")
                        .WithMany("SecurityShifts")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Team");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Checkpoint", "Checkpoint")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeguardSystem.DAL.Entities.SecurityGuard", "Guard")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeguardSystem.DAL.Entities.Location", "Location")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeguardSystem.DAL.Entities.SecurityShift", "Shift")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkpoint");

                    b.Navigation("Guard");

                    b.Navigation("Location");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftIncident", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.ShiftAssignment", "Assignment")
                        .WithMany("ShiftIncidents")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Team", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.SecurityGuard", "Guard")
                        .WithMany()
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.User", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Business", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Checkpoint", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Location", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("SecurityShifts");

                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityGuard", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityShift", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftAssignment", b =>
                {
                    b.Navigation("ShiftIncidents");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftType", b =>
                {
                    b.Navigation("SecurityShifts");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Team", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("SecurityShifts");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.User", b =>
                {
                    b.Navigation("Businesses");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SecurityGuards");
                });
#pragma warning restore 612, 618
        }
    }
}
