// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeguardSystem.DAL;

#nullable disable

namespace SafeguardSystem.DAL.Migrations
{
    [DbContext(typeof(SafeguardDbContext))]
    partial class SafeguardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Business", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("businessId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("BusinessId"), "ascii");

                    b.Property<DateTime>("ContractExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("contractExpiry");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isActive");

                    b.Property<ulong>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "ascii");

                    b.HasKey("BusinessId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "userId");

                    b.ToTable("business", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Checkpoint", b =>
                {
                    b.Property<Guid>("CheckpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("checkpointId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("CheckpointId"), "ascii");

                    b.Property<ulong>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isDeleted");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("locationId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("LocationId"), "ascii");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("CheckpointId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LocationId" }, "locationId");

                    b.ToTable("checkpoint", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Contract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("contractId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ContractId"), "ascii");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contractCode");

                    b.Property<decimal>("ContractValue")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("contractValue");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate");

                    b.Property<ulong>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isDeleted");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)")
                        .HasColumnName("teamId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TeamId"), "ascii");

                    b.HasKey("ContractId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TeamId" }, "teamId");

                    b.ToTable("contract", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("locationId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("LocationId"), "ascii");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)")
                        .HasColumnName("businessId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("BusinessId"), "ascii");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isDeleted");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("placeId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("PlaceId"), "ascii");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("LocationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BusinessId" }, "businessId");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("refreshTokenId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("RefreshTokenId"), "ascii");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createAt");

                    b.Property<ulong>("IsRevoked")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isRevoked");

                    b.Property<string>("RefreshTokenKey")
                        .HasColumnType("longtext")
                        .HasColumnName("refreshTokenKey");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "ascii");

                    b.HasKey("RefreshTokenId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "userId1");

                    b.ToTable("refreshtoken", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("roleId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("RoleId"), "ascii");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("roleName");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("d1616b66-90cc-479f-b45e-1e86378937f7"),
                            RoleName = "Guard"
                        },
                        new
                        {
                            RoleId = new Guid("7a04e1d4-c176-467d-ac7d-6e1433ce6f3e"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("6be95231-36aa-4a26-8c61-b65e040ec32a"),
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = new Guid("be19e4b3-6664-4afd-9ebb-98e0a073edc9"),
                            RoleName = "Business partner"
                        });
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityGuard", b =>
                {
                    b.Property<Guid>("GuardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("guardId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("GuardId"), "ascii");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("identityNumber");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("startDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "ascii");

                    b.HasKey("GuardId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "userId2");

                    b.ToTable("securityguard", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityShift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("shiftId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ShiftId"), "ascii");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("locationId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("LocationId"), "ascii");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)")
                        .HasColumnName("teamId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TeamId"), "ascii");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("typeId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TypeId"), "ascii");

                    b.HasKey("ShiftId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LocationId" }, "locationId1");

                    b.HasIndex(new[] { "TeamId" }, "teamId1");

                    b.HasIndex(new[] { "TypeId" }, "typeId");

                    b.ToTable("securityshift", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("assignmentId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("AssignmentId"), "ascii");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("char(36)")
                        .HasColumnName("checkpointId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("CheckpointId"), "ascii");

                    b.Property<Guid>("GuardId")
                        .HasColumnType("char(36)")
                        .HasColumnName("guardId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("GuardId"), "ascii");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("locationId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("LocationId"), "ascii");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("char(36)")
                        .HasColumnName("shiftId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ShiftId"), "ascii");

                    b.HasKey("AssignmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CheckpointId" }, "checkpointId");

                    b.HasIndex(new[] { "GuardId" }, "guardId");

                    b.HasIndex(new[] { "LocationId" }, "locationId2");

                    b.HasIndex(new[] { "ShiftId" }, "shiftId");

                    b.ToTable("shiftassignment", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftIncident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("incidentId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IncidentId"), "ascii");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assignmentId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("AssignmentId"), "ascii");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Envidence")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("envidence");

                    b.Property<DateTime>("IncidentTime")
                        .HasColumnType("datetime")
                        .HasColumnName("incidentTime");

                    b.Property<ulong>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isDeleted");

                    b.HasKey("IncidentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AssignmentId" }, "assignmentId");

                    b.ToTable("shiftincident", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftType", b =>
                {
                    b.Property<Guid>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("typeId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TypeId"), "ascii");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("endTime");

                    b.Property<ulong>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("startTime");

                    b.HasKey("TypeId")
                        .HasName("PRIMARY");

                    b.ToTable("shifttype", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("teamId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TeamId"), "ascii");

                    b.Property<Guid>("GuardId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("GuardId"), "ascii");

                    b.Property<ulong>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("TeamId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GuardId" }, "IX_team_GuardId");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("userId")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "ascii");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("longtext")
                        .HasColumnName("activationToken");

                    b.Property<DateTime?>("ActivationTokenExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("activationTokenExpiry");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime")
                        .HasColumnName("birthDay");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fullName");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isActive");

                    b.Property<ulong>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isDeleted");

                    b.Property<ulong>("IsEmailConfirmed")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isEmailConfirmed");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("passwordHash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("passwordSalt");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext")
                        .HasColumnName("resetToken");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("resetTokenExpiry");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)")
                        .HasColumnName("RoleID")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("RoleID"), "ascii");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userName");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleID" }, "IX_users_RoleID");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d71a9f93-2bc9-4771-9732-8ee036601ba5"),
                            Avatar = "https://www.freepik.com/free-vector/simple-vibing-cat-square-meme_58459053.htm#fromView=keyword&page=1&position=0&uuid=f4bd18ef-8de6-4b6e-8e68-06073abf526b&query=Animal+Memes",
                            BirthDay = new DateTime(2004, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "a@gmail.com",
                            FullName = "Viet Anh",
                            IsActive = 1ul,
                            IsDeleted = 0ul,
                            IsEmailConfirmed = 1ul,
                            PasswordHash = "$2a$12$wfFP3IPQecfFr1JruMqzae0Z1Mexhvtq/Lhw9luEYNw.0dD/TTzau",
                            PasswordSalt = "",
                            Phone = "0123456789",
                            RoleID = new Guid("7a04e1d4-c176-467d-ac7d-6e1433ce6f3e"),
                            UserName = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("62f56fcb-bcd3-474a-b938-90bda6af54d3"),
                            Avatar = "https://www.freepik.com/free-vector/simple-vibing-cat-square-meme_58459053.htm#fromView=keyword&page=1&position=0&uuid=f4bd18ef-8de6-4b6e-8e68-06073abf526b&query=Animal+Memes",
                            BirthDay = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nam@gmail.com",
                            FullName = "Nhat Nam",
                            IsActive = 1ul,
                            IsDeleted = 0ul,
                            IsEmailConfirmed = 1ul,
                            PasswordHash = "$2a$12$2slGRhLPjB/yiLGpmhxHNOdayMV1MXV/L6EeK3M/VEE04QK31/rcq",
                            PasswordSalt = "",
                            Phone = "0123456789",
                            RoleID = new Guid("6be95231-36aa-4a26-8c61-b65e040ec32a"),
                            UserName = "Manager"
                        });
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Business", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.User", "User")
                        .WithMany("Businesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("business_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Checkpoint", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Location", "Location")
                        .WithMany("Checkpoints")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("checkpoint_ibfk_1");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Contract", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Team", "Team")
                        .WithMany("Contracts")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contract_ibfk_1");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Location", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Business", "Business")
                        .WithMany("Locations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("location_ibfk_1");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refreshtoken_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityGuard", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.User", "User")
                        .WithMany("SecurityGuards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("securityguard_ibfk_2");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityShift", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Location", "Location")
                        .WithMany("SecurityShifts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("securityshift_ibfk_1");

                    b.HasOne("SafeguardSystem.DAL.Entities.Team", "Team")
                        .WithMany("SecurityShifts")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("securityshift_ibfk_3");

                    b.HasOne("SafeguardSystem.DAL.Entities.ShiftType", "Type")
                        .WithMany("SecurityShifts")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("securityshift_ibfk_2");

                    b.Navigation("Location");

                    b.Navigation("Team");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Checkpoint", "Checkpoint")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shiftassignment_ibfk_4");

                    b.HasOne("SafeguardSystem.DAL.Entities.SecurityGuard", "Guard")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shiftassignment_ibfk_2");

                    b.HasOne("SafeguardSystem.DAL.Entities.Location", "Location")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shiftassignment_ibfk_3");

                    b.HasOne("SafeguardSystem.DAL.Entities.SecurityShift", "Shift")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shiftassignment_ibfk_1");

                    b.Navigation("Checkpoint");

                    b.Navigation("Guard");

                    b.Navigation("Location");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftIncident", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.ShiftAssignment", "Assignment")
                        .WithMany("ShiftIncidents")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shiftincident_ibfk_1");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Team", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.SecurityGuard", "Guard")
                        .WithMany()
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.User", b =>
                {
                    b.HasOne("SafeguardSystem.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Business", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Checkpoint", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Location", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("SecurityShifts");

                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityGuard", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.SecurityShift", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftAssignment", b =>
                {
                    b.Navigation("ShiftIncidents");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.ShiftType", b =>
                {
                    b.Navigation("SecurityShifts");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.Team", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("SecurityShifts");
                });

            modelBuilder.Entity("SafeguardSystem.DAL.Entities.User", b =>
                {
                    b.Navigation("Businesses");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SecurityGuards");
                });
#pragma warning restore 612, 618
        }
    }
}
